[build]
  # Build command
  command = "cd farmint-fe && npm run build"
  
  # Output directory (where the built files are)
  publish = "farmint-fe/out"
  
  # Base directory for the build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Disable OpenCollective
  DISABLE_OPENCOLLECTIVE = "1"
  
  # Use npm instead of pnpm for more reliable builds
  NPM_FLAGS = "--legacy-peer-deps"

# Alternative build settings for pnpm (if you prefer pnpm)
# [build]
#   command = "cd farmint-fe && pnpm install --frozen-lockfile=false && pnpm build"
#   publish = "farmint-fe/out"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Special handling for Farcaster miniapp manifest
[[headers]]
  for = "/.well-known/farcaster.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
